# Generated by Django 2.1 on 2019-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('due_date', models.DateTimeField(verbose_name='Дата дедлайна')),
                ('status', models.CharField(choices=[('backlog', 'Очередь'), ('in progress', 'В работе'), ('done', 'Сделано')], default=('backlog', 'Очередь'), max_length=20, verbose_name='Статус')),
                ('time_planned', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Запланированное время')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
